### ISSUE TITLE
Lists.ipynb typos

### ISSUE THREAD

**Issue by HTrammel** [jmportilla/Complete-Python-Bootcamp#6]
The following line appearing after In 44:
Use pop to "pop off" an item form the list. By default pop takes off the last index, but you can also specify whic index to pop off. Let's see an example:

should probably be:
Use pop to "pop off" an item **from** the list. By default pop takes off the last index, but you can also specify **which** index to pop off. Let's see an example:

**Comment by jmportilla** [comment]
Thanks for letting me know! Unfortunately the jupyter notebook doesn't come with a spell-check (although I recently just downloaded one). I'll fix these errors.

Feel free to let me know about anymore (or also feel free to do a pull request).
